### ISSUE TITLE
DEPLOY - wg0.conf file is copied to NAS

### ISSUE THREAD

**Issue by osotechie** [osotechie/nas-docker#5]
The wg0.conf file is still being copied to the NAS.

Check the Copy Content Locally bash script in the [DEPLOY.YML](https://github.com/osotechie/nas-docker/blob/main/.github/workflows/deploy.yml) file.

```yml
      #STEP - Copy Content locally
      #===========================
      #Copy the contents locally for re-use outside pipelines etc           
      - name: Copy Content Locally
        run: |
          #cleanup working files
          rm ./wg0.conf
          scp -r ./* ${{ secrets.NAS_USER }}@${{ secrets.NAS_IP }}:/config/stacks
```
